@api = http://192.168.1.111:5000/

GET {{api}}int/clientlist

###
GET {{api}}int/routeslist

###
GET {{api}}int/advisorslist

###
GET {{api}}int/getproductlist

###
POST {{api}}int/othersupplier
Content-Type: application/json

{
  "Cod": "1"
}

###
GET {{api}}int/enteredlist

###
POST {{api}}int/pppurchase
Content-Type: application/json

{
  "Consecutivo": "2178"
}