#@api = http://192.168.101.8:5000/
@api = http://54.161.22.104:80/

GET {{api}}int/clientlist

###
GET {{api}}int/routeslist

###
GET {{api}}int/advisorslist

###
GET {{api}}int/getproductlist

###
POST {{api}}int/othersupplier
Content-Type: application/json

{
  "Cod": "1"
}

###
GET {{api}}int/enteredlist

###
POST {{api}}int/pppurchase
Content-Type: application/json

{
  "Consecutivo": "2178"
}

###
POST {{api}}int/orderheader
Content-Type: application/json

{
  "NDePedido": 12196
}

###
GET {{api}}int/weekly